.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH cargo 1  "cargo 0.1.0" 
.SH NAME
cargo
.SH SYNOPSIS
\fBcargo\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
cargo\-skeleton(1)
Create and build skeleton packages
.SH VERSION
v0.1.0
