.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH cargo-skeleton-mangen 1  "mangen " 
.SH NAME
cargo\-skeleton\-mangen \- Generate man pages
.SH SYNOPSIS
\fBcargo skeleton mangen\fR [\fB\-\-out\-path\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Generate man pages
.SH OPTIONS
.TP
\fB\-\-out\-path\fR=\fIOUT_PATH\fR [default: .]
Output path for the archive contents
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
